app:
  version: @project.version@

spring:
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: false
    # need to add /client/static as a resource in your IDE
    prefix: classpath:/
  jackson:
    serialization:
      write-dates-as-timestamps: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
          auth: true