app:
  version: @project.version@

last:
  build:
    date: @doodle.build.timestamp@

server:
  servlet-path: /

spring:
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: true
    mode: LEGACYHTML5
    prefix: classpath:static/