app:
  version: @project.version@

last:
  build:
    date: @doodle.build.timestamp@

server:
  servlet-path: /

spring:
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: true
    mode: HTML
    prefix: classpath:static/
  jackson:
    #date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: true
  mail:
    host: smtp.sendgrid.net
    port: 587

  datasource:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    maxActive: 5
    maxIdle: 3
    minIdle: 2
    initialSize: 3
    removeAbandoned: true

flyway:
  enabled: false

