app:
  version: @project.version@

spring:
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: false
    # need to add /client/static as a resource in your IDE
    prefix: classpath:/
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb