app:
  version: @project.version@

last:
  build:
    date: @doodle.build.timestamp@

server:
  servlet-path: /

spring:
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: true
    mode: LEGACYHTML5
    prefix: classpath:static/
  jackson:
    #date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: true