app:
  version: @project.version@

spring:
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:html/
  jackson:
    serialization:
      write-dates-as-timestamps: true

doodle:
  baseUrl: http://doodle-test.com
