/**
 * Created by ratoico on 8/21/15.
 */

module.exports = {
    LOAD_DOODLE_TEMPLATES: "LOAD_DOODLE_TEMPLATES",
    LOAD_DOODLE_TEMPLATES_SUCCESS: "LOAD_DOODLE_TEMPLATES_SUCCESS",
    LOAD_DOODLE_TEMPLATES_FAIL: "LOAD_DOODLE_TEMPLATES_FAIL"
};